/**
 * Re-export of folio-assistant's content-object builders.
 *
 * Every block, chapter and document manifest in this folio imports from here
 * rather than reaching into the platform directly, so the path to
 * folio-assistant is written down exactly once. If you move or re-link the
 * platform checkout, edit this file and `types.ts` beside it — nothing else.
 *
 * Generated by `folio_init`. Safe to edit; not regenerated.
 */

export * from "../../folio-assistant/cat-harness/schemas/builders";
